version: '3.8'

services:
  web:
    build: .
    command: gunicorn --workers 10 messenger.wsgi:application
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env2
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

volumes:
  postgres_data:

